language: java
jdk:
  - oraclejdk7
install: /bin/true
before_script:
  - ./gradlew --version
script: ./gradlew test -PossrhUsername=test -PossrhPassword=test

env:
  - TERM=dumb

after_success:
  - ./gradlew cobertura coveralls
